### ISSUE TITLE
Investigate why minY and maxY calculations may be "reversed"

### ISSUE THREAD

**Issue by jessex** [Recidiviz/supervision-success-component#80]
**What needs to be done? Why does it need to be done?**
In #78, we made it so that the minY and maxY values, which control the y-axis of the chart, are calculated from min and max projections so that the y-axis can be held steady while inputs are experimented with, to help make it easier to see the relative scale of hypothetical changes. However, in that PR, there is some discussion about an initial implementation and test case that revealed it was possible for minY to be greater than maxY. A slight logical change was put into effect to say that maxY was the greater of the min and max projections, and minY the opposite, but this is still a somewhat surprising outcome. We should explore it further and either fix it if there is something to fix, or document in the codebase (where the aforementioned logical change was placed) why it happens.

**Additional context**
See more in #78

**Comment by nasaownsky** [comment]
@jessex I researched the problem for past days, and it seems like the issue is only related to the test case and its mock implementation of functions. You see, with the real data this is **impossible** to have minY greater than maxY, because of peculiarities of the math model. And mock implementation only mocks data from zero to the number of times the tested function will calls. I think this happens due to the new maxY and minY searching method, that implements a few same functions more that one time in actual model, unlike test case, that mocks them only one time each. Mocking them more than one time **does not affect** test results. And I honestly has no idea why this happens, after all the research.

With that in mind I suggest to document that test case (and we also embedded safeguard for cases IF minY will be more than maxY), and move on for now.

**Comment by jessex** [comment]
Thanks for the investigation, @nasaownsky. After reading through your comment a few times and then looking at `produceProjections.test.js` closely, I think I agree with your assessment that the weird test behavior was caused by the fact that the tests are mocking out the actual projection calculation functions with monotonically increasing values. The logic in `produceProjections` that calls out to these functions was originally assuming that `maxY` and `minY` would be properly ordered _because the underlying projection calls functioned as they do_. But in the unit test scenario where those functions are simply mocked out, that assumption may no longer hold and your expectations become undefined. 

While I think it might be wise to update that particular unit test to mock the projection calls in a different way, I don't think it's super important and I'm not sure it's worth the effort at the moment. I'm going to add comments as you suggest and move on. Thanks!
